# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Initiative.create(name: "5th Street Repaving",
  description: "The reworking and repaving of the street.",
  initiative_type: "Charter",
  status: "Pass",
  year: "2008",
  total_contributions: "34001",
  total_expenditures: "12045",
  support_rate: "78",
  ballot_code: "D",
  more_info: "http://propD.com",
)
Initiative.create(name: "Moscone Rebuildiing",
  description: "Shellac on the exterior.",
  initiative_type: "Declaration",
  status: "Pass",
  year: "2010",
  total_contributions: "450021",
  total_expenditures: "199045",
  support_rate: "64",
  ballot_code: "A",
  more_info: "http://propA.com",
)
Initiative.create(name: "Valencia Street Murals",
  description: "3 new murals for the Valencia Street corridor.",
  initiative_type: "Charter",
  status: "Pass",
  year: "2002",
  total_contributions: "34001",
  total_expenditures: "12045",
  support_rate: "52",
  ballot_code: "C",
  more_info: "http://propC.com",
)
Initiative.create(name: "Glen Park Police Station Vehicle Upgrades",
  description: "Better tires and bumpers for police and surveillance vehicles.",
  initiative_type: "Bill",
  status: "Fail",
  year: "2012",
  total_contributions: "24033",
  total_expenditures: "2045",
  support_rate: "44",
  ballot_code: "F",
  more_info: "http://propF.com",
)
Initiative.create(name: "Castro Bike Park",
  description: "Bike park to occupy the edge of the Church St Park.",
  initiative_type: "Declaration",
  status: "Fail",
  year: "2003",
  total_contributions: "16033",
  total_expenditures: "4720",
  support_rate: "25",
  ballot_code: "B",
  more_info: "http://propB.com",
)
Initiative.create(name: "Financial District Sewage Line Refurbishing",
  description: "Replacing the old copper pipes with PVC pipes.",
  initiative_type: "Declaration",
  status: "TBD",
  year: "2020",
  total_contributions: "18020",
  total_expenditures: "2410",
  support_rate: "0",
  ballot_code: "B",
  more_info: "http://propB.com",
)
Initiative.create(name: "Nob Hill Cobblestones",
  description: "Using historic cobblestones on Nob Hill streets.",
  initiative_type: "Charter",
  status: "Pass",
  year: "2013",
  total_contributions: "32520",
  total_expenditures: "6266",
  support_rate: "51",
  ballot_code: "F",
  more_info: "http://propF.com",
)
Initiative.create(name: "Folsom Street Music Festival",
  description: "Commissioning a study of the possibility of a music festival on Folsom St.",
  initiative_type: "Charter",
  status: "Fail",
  year: "2009",
  total_contributions: "10433",
  total_expenditures: "1218",
  support_rate: "47",
  ballot_code: "V",
  more_info: "http://propV.com",
)
Initiative.create(name: "Hayes Market Playground Ornaments",
  description: "Adding more ornaments and visual flair to the playground in Hayes Market.",
  initiative_type: "Bill",
  status: "Pass",
  year: "1998",
  total_contributions: "8250",
  total_expenditures: "3973",
  support_rate: "60",
  ballot_code: "R",
  more_info: "http://propR.com",
)
Initiative.create(name: "San Bruno Children's Orchestra",
  description: "Funding a children's outdoor orchestra that will rehearse and play in community parks.",
  initiative_type: "Bill",
  status: "Pass",
  year: "1992",
  total_contributions: "7299",
  total_expenditures: "425",
  support_rate: "81",
  ballot_code: "G",
  more_info: "http://propG.com",
)
Initiative.create(name: "Sansome Street Corner Park",
  description: "A park at the site of a former convenience store.",
  initiative_type: "Bill",
  status: "Fail",
  year: "1995",
  total_contributions: "23498",
  total_expenditures: "3911",
  support_rate: "39",
  ballot_code: "T",
  more_info: "http://propT.com",
)
Initiative.create(name: "Bike Police Unit",
  description: "Supporting the creation of a bicycle crimes investigation unit.",
  initiative_type: "Bill",
  status: "Fail",
  year: "2005",
  total_contributions: "10983",
  total_expenditures: "7882",
  support_rate: "48",
  ballot_code: "K",
  more_info: "http://propK.com",
)
Initiative.create(name: "Cow Hollow Rainwater Barrel Community Store",
  description: "Purchasing barrels to use to water the Cow Hollow Community Store.",
  initiative_type: "Bill",
  status: "Pass",
  year: "2008",
  total_contributions: "20323",
  total_expenditures: "5290",
  support_rate: "55",
  ballot_code: "A",
  more_info: "http://propK.com",
)
Initiative.create(name: "Market Street Crafts Festival",
  description: "Towards the creation of a knitting festival on Market St.",
  initiative_type: "Bill",
  status: "Fail",
  year: "1983",
  total_contributions: "7230",
  total_expenditures: "1235",
  support_rate: "26",
  ballot_code: "DK",
  more_info: "http://propDK.com",
)
Initiative.create(name: "BART Elevator Canopy",
  description: "Creating canopies for BART elevators so people's activity does not damage them.",
  initiative_type: "Bill",
  status: "Pass",
  year: "2013",
  total_contributions: "32340",
  total_expenditures: "10832",
  support_rate: "65",
  ballot_code: "EP",
  more_info: "http://propEP.com",
)
Initiative.create(name: "Mission Street Bike Lane",
  description: "Adding in a bike lane to Mission Street's busiest corridor.",
  initiative_type: "Bill",
  status: "Pass",
  year: "2009",
  total_contributions: "78201",
  total_expenditures: "12086",
  support_rate: "79",
  ballot_code: "MM",
  more_info: "http://propMM.com",
)
