require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PoliticalcommitteesController do

  # This should return the minimal set of attributes required to create a valid
  # Politicalcommittee. As you add validations to Politicalcommittee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PoliticalcommitteesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all politicalcommittees as @politicalcommittees" do
      politicalcommittee = Politicalcommittee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:politicalcommittees).should eq([politicalcommittee])
    end
  end

  describe "GET show" do
    it "assigns the requested politicalcommittee as @politicalcommittee" do
      politicalcommittee = Politicalcommittee.create! valid_attributes
      get :show, {:id => politicalcommittee.to_param}, valid_session
      assigns(:politicalcommittee).should eq(politicalcommittee)
    end
  end

  describe "GET new" do
    it "assigns a new politicalcommittee as @politicalcommittee" do
      get :new, {}, valid_session
      assigns(:politicalcommittee).should be_a_new(Politicalcommittee)
    end
  end

  describe "GET edit" do
    it "assigns the requested politicalcommittee as @politicalcommittee" do
      politicalcommittee = Politicalcommittee.create! valid_attributes
      get :edit, {:id => politicalcommittee.to_param}, valid_session
      assigns(:politicalcommittee).should eq(politicalcommittee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Politicalcommittee" do
        expect {
          post :create, {:politicalcommittee => valid_attributes}, valid_session
        }.to change(Politicalcommittee, :count).by(1)
      end

      it "assigns a newly created politicalcommittee as @politicalcommittee" do
        post :create, {:politicalcommittee => valid_attributes}, valid_session
        assigns(:politicalcommittee).should be_a(Politicalcommittee)
        assigns(:politicalcommittee).should be_persisted
      end

      it "redirects to the created politicalcommittee" do
        post :create, {:politicalcommittee => valid_attributes}, valid_session
        response.should redirect_to(Politicalcommittee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved politicalcommittee as @politicalcommittee" do
        # Trigger the behavior that occurs when invalid params are submitted
        Politicalcommittee.any_instance.stub(:save).and_return(false)
        post :create, {:politicalcommittee => {}}, valid_session
        assigns(:politicalcommittee).should be_a_new(Politicalcommittee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Politicalcommittee.any_instance.stub(:save).and_return(false)
        post :create, {:politicalcommittee => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested politicalcommittee" do
        politicalcommittee = Politicalcommittee.create! valid_attributes
        # Assuming there are no other politicalcommittees in the database, this
        # specifies that the Politicalcommittee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Politicalcommittee.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => politicalcommittee.to_param, :politicalcommittee => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested politicalcommittee as @politicalcommittee" do
        politicalcommittee = Politicalcommittee.create! valid_attributes
        put :update, {:id => politicalcommittee.to_param, :politicalcommittee => valid_attributes}, valid_session
        assigns(:politicalcommittee).should eq(politicalcommittee)
      end

      it "redirects to the politicalcommittee" do
        politicalcommittee = Politicalcommittee.create! valid_attributes
        put :update, {:id => politicalcommittee.to_param, :politicalcommittee => valid_attributes}, valid_session
        response.should redirect_to(politicalcommittee)
      end
    end

    describe "with invalid params" do
      it "assigns the politicalcommittee as @politicalcommittee" do
        politicalcommittee = Politicalcommittee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Politicalcommittee.any_instance.stub(:save).and_return(false)
        put :update, {:id => politicalcommittee.to_param, :politicalcommittee => {}}, valid_session
        assigns(:politicalcommittee).should eq(politicalcommittee)
      end

      it "re-renders the 'edit' template" do
        politicalcommittee = Politicalcommittee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Politicalcommittee.any_instance.stub(:save).and_return(false)
        put :update, {:id => politicalcommittee.to_param, :politicalcommittee => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested politicalcommittee" do
      politicalcommittee = Politicalcommittee.create! valid_attributes
      expect {
        delete :destroy, {:id => politicalcommittee.to_param}, valid_session
      }.to change(Politicalcommittee, :count).by(-1)
    end

    it "redirects to the politicalcommittees list" do
      politicalcommittee = Politicalcommittee.create! valid_attributes
      delete :destroy, {:id => politicalcommittee.to_param}, valid_session
      response.should redirect_to(politicalcommittees_url)
    end
  end

end
